### ISSUE TITLE
C64 debugger

### ISSUE THREAD

**Issue by emoon** [yupferris/rip-and-tear#1]
Before ProDBG will allow you to do this stuff (and more!) maybe this will be helpful https://sourceforge.net/projects/c64-debugger/ if you haven't used it :)

**Comment by yupferris** [comment]
holy shit, nice! Yeah I've only been using the VICE monitor so far. This looks like it'll be super helpful. Thanks :D

**Comment by emoon** [comment]
np :) I haven't used this myself but looks quite neat :)

**Comment by yupferris** [comment]
Used it a bit now; the interface is a bit daunting and I _really_ wish I could get some more screen real-estate out of it.. but seeing the memory view and some of the other bits is awesome. And it's based on VICE, which is rad. :) def gonna play with this some more!

**Comment by emoon** [comment]
Yeah I hope to have all of this in ProDBG later which will give you more screen real-estate :)
